apiVersion: v1
kind: Pod
metadata:
  name: prometheum-pod
  labels:
    app: prometheum
spec:
  containers:
  - name: storage
    image: localhost/prometheum-storage:latest
    ports:
    - containerPort: 8001
      hostPort: 8001
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    volumeMounts:
    - name: data-volume
      mountPath: /data/volumes
    - name: backup-volume
      mountPath: /data/backup
    - name: config-volume
      mountPath: /data/config
    env:
    - name: LOG_LEVEL
      value: "INFO"
    readinessProbe:
      httpGet:
        path: /health
        port: 8001
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /health
        port: 8001
      initialDelaySeconds: 15
      periodSeconds: 20

  - name: api
    image: localhost/prometheum-api:latest
    ports:
    - containerPort: 8000
      hostPort: 8000
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    env:
    - name: STORAGE_URL
      value: "http://localhost:8001"
    - name: AI_SERVICE_URL
      value: "http://localhost:8002"
    - name: LOG_LEVEL
      value: "INFO"
    readinessProbe:
      httpGet:
        path: /api/health
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /api/health
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 20
    depends_on:
      - storage

  - name: ai
    image: localhost/prometheum-ai:latest
    ports:
    - containerPort: 8002
      hostPort: 8002
    resources:
      limits:
        memory: "2Gi"
        cpu: "1000m"
      requests:
        memory: "1Gi"
        cpu: "500m"
    volumeMounts:
    - name: models-volume
      mountPath: /app/models
    - name: data-volume
      mountPath: /app/data
    env:
    - name: LOG_LEVEL
      value: "INFO"
    - name: MODEL_CACHE_SIZE
      value: "1024"
    readinessProbe:
      httpGet:
        path: /health
        port: 8002
      initialDelaySeconds: 30
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /health
        port: 8002
      initialDelaySeconds: 60
      periodSeconds: 30
    depends_on:
      - storage

  - name: docs
    image: localhost/prometheum-docs:latest
    ports:
    - containerPort: 8080
      hostPort: 8080
    resources:
      limits:
        memory: "256Mi"
        cpu: "200m"
      requests:
        memory: "128Mi"
        cpu: "100m"
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5

  volumes:
  - name: data-volume
    hostPath:
      path: ./data/volumes
      type: DirectoryOrCreate
  - name: backup-volume
    hostPath:
      path: ./data/backup
      type: DirectoryOrCreate
  - name: config-volume
    hostPath:
      path: ./data/config
      type: DirectoryOrCreate
  - name: models-volume
    hostPath:
      path: ./data/models
      type: DirectoryOrCreate

